In [1]:
import numpy as np
print(np.__version__)

1.16.3


### numpy一维数组

In [3]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

In [4]:
x+y

array([3., 6., 9.])

In [5]:
x-y

array([-1., -2., -3.])

In [6]:
x*y

array([ 2.,  8., 18.])

In [7]:
x/y

array([0.5, 0.5, 0.5])

In [8]:
x/2

array([0.5, 1. , 1.5])

### numpy N维数组

In [11]:
a = np.array([[1,2],[3,4]])
b = np.array([[3,0],[0,6]])

In [12]:
a.shape

(2, 2)

In [13]:
a.dtype

dtype('int32')

In [14]:
a+b

array([[ 4,  2],
       [ 3, 10]])

In [15]:
a*b

array([[ 3,  0],
       [ 0, 24]])

In [16]:
a*10

array([[10, 20],
       [30, 40]])

In [18]:
c = np.array([10,20])
a*c

array([[10, 40],
       [30, 80]])

### 访问元素

In [20]:
i = np.array([[51,55],[14,19],[0,4]])
i

array([[51, 55],
       [14, 19],
       [ 0,  4]])

In [21]:
i[0]

array([51, 55])

In [22]:
i[0][1]

55

In [24]:
for row in i:
    print(row)

[51 55]
[14 19]
[0 4]


In [26]:
i = i.flatten()    #展平
i

array([51, 55, 14, 19,  0,  4])

In [28]:
i[np.array([0,2,4])]    #获取索引为0,2,4的元素

array([51, 14,  0])

In [29]:
i>15

array([ True,  True, False,  True, False, False])

In [30]:
i[i>15]    #使用上个boolean型数组，取出了数组的各个元素

array([51, 55, 19])